source "https://rubygems.org"

gem "activerecord", "~> 6.1.7", :require => 'active_record'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'
gem 'rake'
gem 'sqlite3'
gem 'pry'
gem 'require_all'
gem 'rack'
gem 'shotgun'
gem 'sinatra'
gem 'rest-client'